[package]
name = "tsuki-scheduler"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.12.0", optional = true }
chrono = { version = "0.4.38", optional = true }
cron = { version = "0.12.1", optional = true }

tokio = { version = "1.38.0", optional = true }

[features]
tokio = ["dep:tokio", "tokio/sync", "tokio/time", "tokio/rt"]
async-std = ["dep:async-std"]
cron = ["dep:cron", "dep:chrono"]
chrono = ["dep:chrono"]
