[package]
name = "tsuki-scheduler"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.12.0", optional = true }

tokio = { version = "1.38.0", optional = true }

[features]
tokio = ["dep:tokio", "tokio/sync", "tokio/time", "tokio/rt"]
async-std = ["dep:async-std", ]
