name: Release

on:
  push:
    branches: ["release"]
  pull_request:
    branches: ["release"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  check:
    needs: test
    if: github.event_name == 'release' && github.event.action == 'created'
    runs-on: ubuntu-latest
    steps:
      - name: Run clippy
        run: cargo clippy --all-features
      - name: Run fmt
        run: cargo fmt --all -- --check
      - name: publish dry run
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }} --dry-run
      - name: publish
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
